### ISSUE TITLE
Retheme removes GitHub code review comments

### ISSUE THREAD

**Issue by Nezteb** [kwhitley/retheme-site#1]
Normal comments work fine, but comments attached to code diffs are removed from the normal PR view:
![Screen Shot 2022-04-21 at 10 54 10 AM](https://user-images.githubusercontent.com/3588798/164744386-ae133336-ca48-4a05-abbf-436d7029e92d.png)

Even in the "Files changed" tab the comments are invisible but you can see the empty lines where they would normally show up.
<img width="1275" alt="Screen Shot 2022-04-21 at 10 53 57 AM" src="https://user-images.githubusercontent.com/3588798/164744458-6e5b106a-9826-4cc8-8cad-fc570b221788.png">

**Comment by kwhitley** [comment]
Yikes!  Taking a look... in the meantime, turn off Global Themes (should be the only thing affecting here), and expect a fix in a minute or two!

**Comment by kwhitley** [comment]
Closing the ticket for now, marking as resolved :)

(here it is with updated global theme enabled)
![image](https://user-images.githubusercontent.com/865416/164766836-fa5625c6-812b-4754-990d-7da0c11adc0c.png)
